### ISSUE TITLE
Factor of sqrt(2) in unvec_symm and vec_symm?

### ISSUE THREAD

**Issue by tjdiamandis** [matbesancon/MathOptSetDistances.jl#21]
I think the [`unvec_symm` and `vec_symm` functions](https://github.com/matbesancon/MathOptSetDistances.jl/blob/55773d571270948cf9e9d05eb74a9cb3ba5629cb/src/projections.jl#L95) should have a sqrt(2) factor on the off-diagonal entires to preserve the inner product, i.e., `Tr(CX) = vec(C)' * vec(X)` (see [SCS README](https://github.com/cvxgrp/scs)).

```
X = [ X11 X12 ... X1k
      X21 X22 ... X2k
      ...
      Xk1 Xk2 ... Xkk ]
```
becomes
```
vec(X) = (X11, sqrt(2)*X21, ..., sqrt(2)*Xk1, X22, sqrt(2)*X32, ..., Xkk).
```

**Comment by matbesancon** [comment]
yes it's been mentionned by @joaquimg in an earlier issue. A PR would be very much welcome on this part

**Comment by matbesancon** [comment]
Also pinging @blegat on that

**Comment by tjdiamandis** [comment]
Actually, I was incorrect about the factor of sqrt(2) if MathOptInterface convention is used (see [`AbstractSymmetricMatrixSetTriangle`](https://jump.dev/MathOptInterface.jl/stable/apireference/#MathOptInterface.AbstractSymmetricMatrixSetTriangle)).

Didn't realize the mismatch between the MOI and SCS vectorizations. The former has no scaling but does not preserve the inner product when vectorized.

**Comment by matbesancon** [comment]
> the factor of sqrt(2) if MathOptInterface convention is used

now that you mention it, I think it was settled somewhere with the MOI convention being favoured

**Comment by tjdiamandis** [comment]
Ah, I found it [here](https://github.com/jump-dev/MathOptInterface.jl/issues/176). I think a note in the docstring that mentions this would be valuable. I can add this.

**Comment by matbesancon** [comment]
That would be great yes thank you!

**Comment by matbesancon** [comment]
fixed in the PR with a precision thanks!
