### ISSUE TITLE
Test projections against AD

### ISSUE THREAD

**Issue by matbesancon** [matbesancon/MathOptSetDistances.jl#8]
AD should work on these functions and let us check automatically if the automatic gradient is equal to the analytical form we provide

**Comment by AKS1996** [comment]
a really good point. that might even reduce the code for the projection gradients

**Comment by AKS1996** [comment]
oh. saw #6 just now :sweat_smile:

**Comment by matbesancon** [comment]
haha yes, I think we should keep the manual checks for now, but:
1. test against another diff system, ForwardDiff or FiniteDiff
2. implement ChainRules later

**Comment by matbesancon** [comment]
Done against FiniteDifference with accuracy tolerance in #15
